#!/usr/bin/env bash

FILE=$1

if [[ -z "$N" ]] || [[ -z "$I" ]] || [[ -z "$P" ]] || [[ -z "$SPC" ]] || [[ -z "$PVK" ]] || [[ -z "$1" ]]; then
    echo "Usage: N=<name> I=<info> P=<pw> SPC=<spc file> PVK=<pvk file> windowsign.sh <file.exe>"
    exit 1
fi

if ! which signcode > /dev/null; then
    echo "signcode command not found"
    exit 1
fi

if ! which signcode > /dev/null; then
    echo "signcode command not found"
    echo "Try: sudo apt-get install mono-devel"
    exit 1
fi

if ! which expect > /dev/null; then
    echo "expect command not found"
    echo "Try: sudo apt-get install mono-devel"
    exit 1
fi

set -eu

echo "
    spawn signcode \
    -spc $SPC \
    -v $PVK \
    -a sha1 -$ commercial \
    -n $N \
    -i $I \
    -t http://timestamp.verisign.com/scripts/timstamp.dll \
    -tr 10 \
    $1

    expect \"Enter password for $PVK:\"
    send -- \"$P\r\"
    expect eof
    lassign [wait] pid spawnid os_error_flag value
    exit \$value" | expect > /dev/null && echo "Signed $1"

